### ISSUE TITLE
Adding a link back to Employer page in tweet?

### ISSUE THREAD

**Issue by michaelwood** [alifensome/gender-pay-gap-bot#2]
It might be nice to link back to an employer page e.g. https://gender-pay-gap.service.gov.uk/Employer/gDuQKC7x this could help build confidence in the company match and give people the historical reports too which are available on that page.

If the ID wasn't available then perhaps even just a handy link to the https://gender-pay-gap.service.gov.uk/viewing/search-results?t=1&search=UBS&orderBy=relevance

**Comment by alifensome** [comment]
> It might be nice to link back to an employer page e.g. https://gender-pay-gap.service.gov.uk/Employer/gDuQKC7x this could help build confidence in the company match and give people the historical reports too which are available on that page.
> 
> If the ID wasn't available then perhaps even just a handy link to the https://gender-pay-gap.service.gov.uk/viewing/search-results?t=1&search=UBS&orderBy=relevance

Hello @michaelwood, 

Thanks for your suggestion, this would go against twitters anti spam guidelines and almost certainly result in us getting banned within a few hours... like last year. Its much better individuals on twitter post those links with hashtags and tag companies themselves. Last year we were banned for using hashtags and tweeting at the companies by lunchtime this year we made it a full week!
